version: 'test-{build}'
environment:
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '10'
    - nodejs_version: '12'
platform:
  - x86
  - x64
clone_folder: 'c:\projects\%APPVEYOR_PROJECT_NAME%'
install:
  - ps: 'Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform'
  - npm install
test_script:
  - echo %cd%
  - node --version
  - npm --version
  - 'npm run test:package'
  - 'npm run test:unit'
  - 'npm run test:integration'
build: 'off'
